# Generated by Django 4.2.5 on 2023-10-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieScratch', '0002_director_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='movies_directed', to='MovieScratch.director'),
        ),
    ]
